### ISSUE TITLE
Comments for GRAKN.AI's "Querying with Graql" documentation

### ISSUE THREAD

**Issue by stichbury** [graknlabs/docs#42]
Please leave comments and feedback about our "Querying with Graql" example here.

Insert usual disclaimer about being nice.

**Comment by haikalpribadi** [comment]
are we missing keywords from analytics here? like min, max, median, etc?

**Comment by stichbury** [comment]
Aha - you're right, and likewise for aggregate queries. I need to sort out those keywords anyway: the ordering isn't correct at present (alphabetical doesn't make sense). Thanks!

**Comment by Phil-Young-Bose** [comment]
The CLI (graql.sh in interactive mode, i.e. without -f) seems to only allow entering a query on one line. The example at https://grakn.ai/pages/documentation/get-started/setup-guide.html does show this ("match $x isa person, has identifier $n;"). However, one can paste a multiline query into the GUI, or run via "graql.sh -f <SCRIPT>". This caused me to suspect that the CLI error was due to a system configuration issue, which consumed some time to resolve. I could be wrong, but I don't see this limitation/gotcha in the docs or as an open issue.

**Comment by burukuru** [comment]
@Phil-Young-Bose Hi Phil, would you mind posting this comment as an issue on our main repository at https://github.com/graknlabs/grakn?
The docs repository has been merged into the main one and we will make this private shortly.

**Comment by Phil-Young-Bose** [comment]
Sure thing. 
FWIW, the issue I made is https://github.com/graknlabs/grakn/issues/2171
